name: Environment Scope Tests

on:
  workflow_dispatch:

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bash environment
        shell: bash
        run: env

      - name: Bash environment executed script
        shell: bash
        run: chmod +x script.sh && ./script.sh | sort > executed_output.txt

      - name: Bash environment sourced script
        shell: bash
        run: source script.sh | sort > sourced_output.txt

      - name: Compare outputs
        run: diff sourced_output.txt executed_output.txt
