name: Environment Scope Tests

on:
  workflow_dispatch:

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bash environment
        shell: bash
        run: |
          env | sort > env.txt
          chmod +x script.sh && ./script.sh | sort > bash_executed.txt
          source script.sh | sort > bash_sourced.txt
          echo "executed"
          diff env.txt bash_executed.txt
          echo "sourced"
          diff env.txt bash_sourced.txt
          
      - name: Python inline script
        shell: python
        run: |
          import os

          def print_env_variables():
              for key, value in os.environ.items():
                  print(f"{key}={value}")
          
          if __name__ == "__main__":
              print_env_variables()
